/**
 * @file cciMap.js
 * @description Static mapping of DISA Control Correlation Identifier (CCI) IDs to
 * NIST SP 800-53 Revision 5 security control identifiers and titles.
 *
 * Sourced from the Defense Information Systems Agency (DISA) CCI list, mapped to
 * NIST SP 800-53 Rev 5 controls. CCI provides a granular standard means to
 * correlate policy, procedures, and standards with technical system security
 * requirements.
 *
 * References:
 *   - DISA CCI List: https://public.cyber.mil/stigs/cci/
 *   - NIST SP 800-53 Rev 5: https://csrc.nist.gov/publications/detail/sp/800-53/rev-5/final
 */

/**
 * @typedef {Object} CCIEntry
 * @property {string} control - NIST SP 800-53 Rev 5 control identifier (e.g., "AC-3", "IA-5(1)")
 * @property {string} title   - Short descriptive title of the control or control enhancement
 */

/**
 * Mapping of CCI identifiers to NIST SP 800-53 Rev 5 controls.
 * Keys are zero-padded six-digit CCI strings (e.g., "CCI-000002").
 *
 * @type {Object.<string, CCIEntry>}
 */
export const CCI_MAP = {
  "CCI-000002": { control: "AC-1(a)(1)",    title: "Policy and Procedures" },
  "CCI-000003": { control: "AC-1(a)(2)",    title: "Policy and Procedures" },
  "CCI-000004": { control: "AC-1(b)(1)",    title: "Policy and Procedures" },
  "CCI-000007": { control: "AC-1(b)(2)",    title: "Policy and Procedures" },
  "CCI-000008": { control: "AC-2(a)",       title: "Account Management" },
  "CCI-000009": { control: "AC-2(b)",       title: "Account Management" },
  "CCI-000010": { control: "AC-2(c)",       title: "Account Management" },
  "CCI-000011": { control: "AC-2(d)",       title: "Account Management" },
  "CCI-000012": { control: "AC-2(e)",       title: "Account Management" },
  "CCI-000013": { control: "AC-2(f)",       title: "Account Management" },
  "CCI-000014": { control: "AC-2(g)",       title: "Account Management" },
  "CCI-000015": { control: "AC-2(c)",       title: "Account Management" },
  "CCI-000016": { control: "AC-2(d)",       title: "Account Management" },
  "CCI-000017": { control: "AC-2(e)",       title: "Account Management" },
  "CCI-000018": { control: "AC-2(j)",       title: "Account Management" },
  "CCI-000040": { control: "AC-3",          title: "Access Enforcement" },
  "CCI-000044": { control: "AC-7(a)",       title: "Unsuccessful Logon Attempts" },
  "CCI-000045": { control: "AC-7(b)",       title: "Unsuccessful Logon Attempts" },
  "CCI-000046": { control: "AC-7(c)",       title: "Unsuccessful Logon Attempts" },
  "CCI-000054": { control: "AC-10",         title: "Concurrent Session Control" },
  "CCI-000057": { control: "AC-11(a)",      title: "Device Lock" },
  "CCI-000058": { control: "AC-11(b)",      title: "Device Lock" },
  "CCI-000060": { control: "AC-11(1)",      title: "Device Lock | Pattern-Hiding Displays" },
  "CCI-000061": { control: "AC-12",         title: "Session Termination" },
  "CCI-000067": { control: "AC-17(2)",      title: "Remote Access | Protection of Confidentiality/Integrity" },
  "CCI-000068": { control: "IA-7",          title: "Cryptographic Module Authentication" },
  "CCI-000130": { control: "AU-3(a)",       title: "Content of Audit Records" },
  "CCI-000131": { control: "AU-3(b)",       title: "Content of Audit Records" },
  "CCI-000132": { control: "AU-3(c)",       title: "Content of Audit Records" },
  "CCI-000133": { control: "AU-3(d)",       title: "Content of Audit Records" },
  "CCI-000134": { control: "AU-3(e)",       title: "Content of Audit Records" },
  "CCI-000135": { control: "AU-3(f)",       title: "Content of Audit Records" },
  "CCI-000139": { control: "AU-5(a)",       title: "Response to Audit Logging Process Failures" },
  "CCI-000140": { control: "AU-5(b)",       title: "Response to Audit Logging Process Failures" },
  "CCI-000154": { control: "AU-7(1)",       title: "Audit Record Review, Analysis, and Reporting | Automatic Processing" },
  "CCI-000158": { control: "AU-9",          title: "Protection of Audit Information" },
  "CCI-000159": { control: "AU-9(a)",       title: "Protection of Audit Information" },
  "CCI-000163": { control: "AU-9(3)",       title: "Protection of Audit Information | Cryptographic Protection" },
  "CCI-000169": { control: "AU-12(a)",      title: "Audit Record Generation" },
  "CCI-000170": { control: "AU-12(b)",      title: "Audit Record Generation" },
  "CCI-000171": { control: "AU-12(c)",      title: "Audit Record Generation" },
  "CCI-000172": { control: "AU-12(d)",      title: "Audit Record Generation" },
  "CCI-000185": { control: "CM-1(a)(1)",    title: "Configuration Management Policy and Procedures" },
  "CCI-000192": { control: "IA-5(1)(a)",    title: "Authenticator Management | Password-Based Authentication (Uppercase)" },
  "CCI-000193": { control: "IA-5(1)(a)",    title: "Authenticator Management | Password-Based Authentication (Lowercase)" },
  "CCI-000194": { control: "IA-5(1)(a)",    title: "Authenticator Management | Password-Based Authentication (Numeric)" },
  "CCI-000195": { control: "IA-5(1)(b)",    title: "Authenticator Management | Password-Based Authentication (Min Lifetime)" },
  "CCI-000196": { control: "IA-5(1)(c)",    title: "Authenticator Management | Password-Based Authentication (Max Lifetime)" },
  "CCI-000197": { control: "IA-5(1)(d)",    title: "Authenticator Management | Password-Based Authentication (Reuse)" },
  "CCI-000198": { control: "IA-5(1)(e)",    title: "Authenticator Management | Password-Based Authentication (Encryption)" },
  "CCI-000199": { control: "IA-5(1)(f)",    title: "Authenticator Management | Password-Based Authentication (Min Length)" },
  "CCI-000200": { control: "IA-5(1)(g)",    title: "Authenticator Management | Password-Based Authentication (Complexity)" },
  "CCI-000205": { control: "IA-5(2)(a)",    title: "Authenticator Management | PKI-Based Authentication" },
  "CCI-000213": { control: "AC-3",          title: "Access Enforcement" },
  "CCI-000214": { control: "AC-3(1)",       title: "Access Enforcement | Restricted Access to Privileged Functions" },
  "CCI-000215": { control: "AC-3(2)",       title: "Access Enforcement | Dual Authorization" },
  "CCI-000225": { control: "AC-6",          title: "Least Privilege" },
  "CCI-000226": { control: "AC-6(1)",       title: "Least Privilege | Authorize Access to Security Functions" },
  "CCI-000230": { control: "AC-6(5)",       title: "Least Privilege | Privileged Accounts" },
  "CCI-000238": { control: "AC-6(9)",       title: "Least Privilege | Log Use of Privileged Functions" },
  "CCI-000239": { control: "AC-6(10)",      title: "Least Privilege | Prohibit Non-Privileged Users" },
  "CCI-000258": { control: "AC-17",         title: "Remote Access" },
  "CCI-000295": { control: "CM-3",          title: "Configuration Change Control" },
  "CCI-000296": { control: "CM-3(a)",       title: "Configuration Change Control" },
  "CCI-000318": { control: "CM-4",          title: "Security and Privacy Impact Analysis" },
  "CCI-000345": { control: "CM-5",          title: "Access Restrictions for Change" },
  "CCI-000366": { control: "CM-6(a)",       title: "Configuration Settings" },
  "CCI-000370": { control: "CM-6(b)",       title: "Configuration Settings" },
  "CCI-000381": { control: "CM-7(a)",       title: "Least Functionality" },
  "CCI-000382": { control: "CM-7(b)",       title: "Least Functionality" },
  "CCI-000764": { control: "IA-2",          title: "Identification and Authentication (Organizational Users)" },
  "CCI-000765": { control: "IA-2(1)",       title: "Identification and Authentication | Multi-Factor Authentication to Privileged Accounts" },
  "CCI-000766": { control: "IA-2(2)",       title: "Identification and Authentication | Multi-Factor Authentication to Non-Privileged Accounts" },
  "CCI-000767": { control: "IA-2(3)",       title: "Identification and Authentication | Local Access to Privileged Accounts" },
  "CCI-000768": { control: "IA-2(4)",       title: "Identification and Authentication | Local Access to Non-Privileged Accounts" },
  "CCI-000778": { control: "IA-3",          title: "Device Identification and Authentication" },
  "CCI-000795": { control: "IA-4(e)",       title: "Identifier Management" },
  "CCI-000803": { control: "IA-6",          title: "Authentication Feedback" },
  "CCI-000804": { control: "IA-7",          title: "Cryptographic Module Authentication" },
  "CCI-000879": { control: "MA-2(a)",       title: "Controlled Maintenance" },
  "CCI-000946": { control: "PE-2(a)",       title: "Physical Access Authorizations" },
  "CCI-001082": { control: "SC-2",          title: "Separation of System and User Functionality" },
  "CCI-001084": { control: "SC-3",          title: "Security Function Isolation" },
  "CCI-001090": { control: "SC-4",          title: "Information in Shared System Resources" },
  "CCI-001095": { control: "SC-5",          title: "Denial of Service Protection" },
  "CCI-001133": { control: "SC-10",         title: "Network Disconnect" },
  "CCI-001135": { control: "SC-10",         title: "Network Disconnect" },
  "CCI-001167": { control: "SC-18(1)",      title: "Mobile Code | Identify Unacceptable Code / Take Corrective Actions" },
  "CCI-001170": { control: "SI-3",          title: "Malicious Code Protection" },
  "CCI-001184": { control: "SC-23",         title: "Session Authenticity" },
  "CCI-001185": { control: "SC-23(1)",      title: "Session Authenticity | Invalidate Session Identifiers at Logout" },
  "CCI-001186": { control: "SC-23(3)",      title: "Session Authenticity | Unique Session Identifiers with Randomization" },
  "CCI-001187": { control: "SC-23(5)",      title: "Session Authenticity | Allowed Certificate Authorities" },
  "CCI-001188": { control: "AC-2(5)",       title: "Account Management | Inactivity Logout" },
  "CCI-001199": { control: "SC-28",         title: "Protection of Information at Rest" },
  "CCI-001200": { control: "SC-28(1)",      title: "Protection of Information at Rest | Cryptographic Protection" },
  "CCI-001312": { control: "SI-11(a)",      title: "Error Handling" },
  "CCI-001313": { control: "SI-11(b)",      title: "Error Handling" },
  "CCI-001314": { control: "SI-11",         title: "Error Handling" },
  "CCI-001368": { control: "AC-4",          title: "Information Flow Enforcement" },
  "CCI-001384": { control: "AC-8(a)",       title: "System Use Notification" },
  "CCI-001385": { control: "AC-8(b)",       title: "System Use Notification" },
  "CCI-001386": { control: "AC-8(c)(1)",    title: "System Use Notification" },
  "CCI-001387": { control: "AC-8(c)(2)",    title: "System Use Notification" },
  "CCI-001388": { control: "AC-8(c)(3)",    title: "System Use Notification" },
  "CCI-001389": { control: "SC-12",         title: "Cryptographic Key Establishment and Management" },
  "CCI-001390": { control: "SC-12(1)",      title: "Cryptographic Key Establishment and Management | Availability" },
  "CCI-001391": { control: "SC-12(2)",      title: "Cryptographic Key Establishment and Management | Symmetric Keys" },
  "CCI-001392": { control: "SC-12(3)",      title: "Cryptographic Key Establishment and Management | Asymmetric Keys" },
  "CCI-001402": { control: "SC-13",         title: "Cryptographic Protection" },
  "CCI-001403": { control: "AC-2(4)",       title: "Account Management | Automated Audit Actions" },
  "CCI-001404": { control: "AC-2(4)",       title: "Account Management | Automated Audit Actions" },
  "CCI-001405": { control: "AC-2(4)",       title: "Account Management | Automated Audit Actions" },
  "CCI-001406": { control: "AC-2(4)",       title: "Account Management | Automated Audit Actions" },
  "CCI-001414": { control: "AC-17(1)",      title: "Remote Access | Monitoring and Control" },
  "CCI-001499": { control: "CM-11",         title: "User-Installed Software" },
  "CCI-001544": { control: "AC-6(8)",       title: "Least Privilege | Security Functions" },
  "CCI-001546": { control: "AC-2(1)",       title: "Account Management | Automated System Account Management" },
  "CCI-001547": { control: "AC-2(2)",       title: "Account Management | Automated Temporary and Emergency Account Management" },
  "CCI-001619": { control: "IA-5(1)(h)",    title: "Authenticator Management | Password-Based Authentication (Special Characters)" },
  "CCI-001620": { control: "IA-5(1)(i)",    title: "Authenticator Management | Password-Based Authentication (Prohibit Reuse)" },
  "CCI-001621": { control: "AC-12(1)",      title: "Session Termination | User-Initiated Logouts / Message Displays" },
  "CCI-001625": { control: "SA-10",         title: "Developer Configuration Management" },
  "CCI-001632": { control: "SC-8",          title: "Transmission Confidentiality and Integrity" },
  "CCI-001633": { control: "SC-8(1)",       title: "Transmission Confidentiality and Integrity | Cryptographic Protection" },
  "CCI-001665": { control: "SC-39",         title: "Process Isolation" },
  "CCI-001749": { control: "CM-11(2)",      title: "User-Installed Software | Software Installation with Privileged Status" },
  "CCI-001752": { control: "CM-8(3)(a)",    title: "System Component Inventory | Automated Unauthorized Component Detection" },
  "CCI-001753": { control: "CM-8(3)(b)",    title: "System Component Inventory | Automated Unauthorized Component Detection" },
  "CCI-001754": { control: "CM-8(5)",       title: "System Component Inventory | No Duplicate Accounting of Components" },
  "CCI-001755": { control: "IA-3(1)",       title: "Device Identification and Authentication | Cryptographic Bidirectional Authentication" },
  "CCI-001762": { control: "CM-7(5)(b)",    title: "Least Functionality | Authorized Software / Allow-by-Exception" },
  "CCI-001812": { control: "AU-11",         title: "Audit Record Retention" },
  "CCI-001813": { control: "CM-6(1)",       title: "Configuration Settings | Automated Management / Application / Verification" },
  "CCI-001814": { control: "CM-6(1)",       title: "Configuration Settings | Automated Management / Application / Verification" },
  "CCI-001851": { control: "AU-4(1)",       title: "Audit Log Storage Capacity | Transfer to Alternate Storage" },
  "CCI-001852": { control: "AU-11",         title: "Audit Record Retention" },
  "CCI-001853": { control: "AU-12(1)",      title: "Audit Record Generation | System-Wide and Time-Correlated Audit Trail" },
  "CCI-001854": { control: "AU-12(3)",      title: "Audit Record Generation | Changes by Authorized Individuals" },
  "CCI-001855": { control: "AU-13",         title: "Monitoring for Information Disclosure" },
  "CCI-001862": { control: "SI-2(6)",       title: "Flaw Remediation | Removal of Previous Versions of Software/Firmware" },
  "CCI-001876": { control: "SI-7(1)",       title: "Software, Firmware, and Information Integrity | Integrity Checks" },
  "CCI-001877": { control: "SI-7(2)",       title: "Software, Firmware, and Information Integrity | Automated Notifications of Integrity Violations" },
  "CCI-001878": { control: "SI-7(5)",       title: "Software, Firmware, and Information Integrity | Automated Response to Integrity Violations" },
  "CCI-001879": { control: "SI-7(7)",       title: "Software, Firmware, and Information Integrity | Integration of Detection and Response" },
  "CCI-001880": { control: "SI-7(14)",      title: "Software, Firmware, and Information Integrity | Binary or Machine Executable Code" },
  "CCI-001891": { control: "AU-8(1)",       title: "Time Stamps | Synchronization with Authoritative Time Source" },
  "CCI-001892": { control: "AU-8(1)(b)",    title: "Time Stamps | Synchronization with Authoritative Time Source" },
  "CCI-001893": { control: "AU-8(2)",       title: "Time Stamps | Secondary Authoritative Time Source" },
  "CCI-001894": { control: "AU-8(a)",       title: "Time Stamps" },
  "CCI-001895": { control: "AU-8(b)",       title: "Time Stamps" },
  "CCI-002001": { control: "IA-2(11)",      title: "Identification and Authentication | Remote Access - Separate Device" },
  "CCI-002002": { control: "IA-2(12)",      title: "Identification and Authentication | Acceptance of PIV Credentials" },
  "CCI-002004": { control: "IA-2(8)",       title: "Identification and Authentication | Access to Accounts - Replay Resistant" },
  "CCI-002007": { control: "IA-2(6)",       title: "Identification and Authentication | Access to Accounts - Separate Device" },
  "CCI-002009": { control: "IA-2(3)",       title: "Identification and Authentication | Local Access to Privileged Accounts" },
  "CCI-002010": { control: "IA-8(2)",       title: "Identification and Authentication (Non-Organizational Users) | Acceptance of External Authenticators" },
  "CCI-002016": { control: "IA-11",         title: "Re-Authentication" },
  "CCI-002038": { control: "IA-5(13)",      title: "Authenticator Management | Expiration of Cached Authenticators" },
  "CCI-002039": { control: "IA-5(14)",      title: "Authenticator Management | Managing Content of PKI Trust Stores" },
  "CCI-002040": { control: "IA-5(15)",      title: "Authenticator Management | GSA-Approved Products and Services" },
  "CCI-002041": { control: "IA-5(16)",      title: "Authenticator Management | In-Person or Trusted Third-Party Registration" },
  "CCI-002061": { control: "AC-2(12)",      title: "Account Management | Account Monitoring for Atypical Usage" },
  "CCI-002062": { control: "AC-2(13)",      title: "Account Management | Disable Accounts for High-Risk Individuals" },
  "CCI-002063": { control: "AC-2(7)",       title: "Account Management | Privileged User Accounts" },
  "CCI-002100": { control: "AC-17(4)",      title: "Remote Access | Privileged Commands/Access" },
  "CCI-002105": { control: "AC-20",         title: "Use of External Systems" },
  "CCI-002132": { control: "AC-2(11)",      title: "Account Management | Usage Conditions" },
  "CCI-002133": { control: "AC-2(10)",      title: "Account Management | Shared and Group Account Credential Change" },
  "CCI-002142": { control: "AC-3(4)",       title: "Access Enforcement | Discretionary Access Control" },
  "CCI-002149": { control: "AC-3(8)",       title: "Access Enforcement | Revocation of Access Authorizations" },
  "CCI-002165": { control: "AC-3(9)",       title: "Access Enforcement | Controlled Release" },
  "CCI-002176": { control: "AC-3(13)",      title: "Access Enforcement | Attribute-Based Access Control" },
  "CCI-002184": { control: "AC-6(7)",       title: "Least Privilege | Review of User Privileges" },
  "CCI-002192": { control: "AC-6(2)",       title: "Least Privilege | Non-Privileged Access for Non-Security Functions" },
  "CCI-002205": { control: "AC-14",         title: "Permitted Actions Without Identification or Authentication" },
  "CCI-002234": { control: "AC-6(9)",       title: "Least Privilege | Log Use of Privileged Functions" },
  "CCI-002235": { control: "AC-6(10)",      title: "Least Privilege | Prohibit Non-Privileged Users from Executing Privileged Functions" },
  "CCI-002361": { control: "AC-12",         title: "Session Termination" },
  "CCI-002385": { control: "SI-10",         title: "Information Input Validation" },
  "CCI-002418": { control: "SC-8",          title: "Transmission Confidentiality and Integrity" },
  "CCI-002419": { control: "SC-8(1)",       title: "Transmission Confidentiality and Integrity | Cryptographic Protection" },
  "CCI-002420": { control: "SC-8(1)",       title: "Transmission Confidentiality and Integrity | Cryptographic Protection" },
  "CCI-002421": { control: "SC-8(2)",       title: "Transmission Confidentiality and Integrity | Pre/Post Transmission Handling" },
  "CCI-002422": { control: "SC-8(3)",       title: "Transmission Confidentiality and Integrity | Cryptographic Protection for Message Externals" },
  "CCI-002423": { control: "SC-8(4)",       title: "Transmission Confidentiality and Integrity | Conceal or Randomize Communications" },
  "CCI-002427": { control: "SC-9",          title: "Transmission Confidentiality" },
  "CCI-002430": { control: "SC-13",         title: "Cryptographic Protection" },
  "CCI-002450": { control: "SC-13(1)",      title: "Cryptographic Protection | FIPS-Validated Cryptography" },
  "CCI-002454": { control: "SC-15",         title: "Collaborative Computing Devices and Applications" },
  "CCI-002461": { control: "SC-17",         title: "Public Key Infrastructure Certificates" },
  "CCI-002470": { control: "SC-20",         title: "Secure Name/Address Resolution Service (Authoritative Source)" },
  "CCI-002471": { control: "SC-20(a)",      title: "Secure Name/Address Resolution Service" },
  "CCI-002472": { control: "SC-20(b)",      title: "Secure Name/Address Resolution Service" },
  "CCI-002475": { control: "SC-28(1)",      title: "Protection of Information at Rest | Cryptographic Protection" },
  "CCI-002476": { control: "SC-28(2)",      title: "Protection of Information at Rest | Off-Line Storage" },
  "CCI-002530": { control: "SI-2(5)",       title: "Flaw Remediation | Automatic Software/Firmware Updates" },
  "CCI-002534": { control: "SI-3(1)",       title: "Malicious Code Protection | Signature Updates" },
  "CCI-002605": { control: "SI-2(a)",       title: "Flaw Remediation" },
  "CCI-002607": { control: "SI-2(c)",       title: "Flaw Remediation" },
  "CCI-002617": { control: "SI-2(2)",       title: "Flaw Remediation | Automated Flaw Remediation Status" },
  "CCI-002696": { control: "SI-6(a)",       title: "Security and Privacy Function Verification" },
  "CCI-002699": { control: "SI-6(b)",       title: "Security and Privacy Function Verification" },
  "CCI-002702": { control: "SI-6(d)",       title: "Security and Privacy Function Verification" },
  "CCI-002754": { control: "SI-7(15)",      title: "Software, Firmware, and Information Integrity | Code Authentication" },
}
